### ISSUE TITLE
NumberIsTooSmallException Exception

### ISSUE THREAD

**Issue by thomcz** [HRVBand/hrv-lib#4]
User Reports this Exception, but no message
```
org.apache.commons.math3.exception.NumberIsTooSmallException: number of points (0)
	at org.apache.commons.math3.analysis.interpolation.SplineInterpolator.interpolate(SplineInterpolator.java:74)
	at hrv.calc.manipulator.HRVSplineInterpolator.manipulate(HRVSplineInterpolator.java:24)
	at hrv.calc.manipulator.HRVMultiDataManipulator.manipulate(HRVMultiDataManipulator.java:17)
	at hrv.band.app.control.HRVCalculatorFacade.getPowerSpectrum(HRVCalculatorFacade.java:127)
	at hrv.band.app.control.HRVCalculatorFacade.getLF(HRVCalculatorFacade.java:62)
	at hrv.band.app.control.Measurement.from(Measurement.java:200)
	at hrv.band.app.view.fragment.MeasuringFragment$ProgressBarAnimatorListener.createMeasurement(MeasuringFragment.java:424)
	at hrv.band.app.view.fragment.MeasuringFragment$ProgressBarAnimatorListener.onAnimationEnd(MeasuringFragment.java:397)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1149)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1309)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:925)
	at android.view.Choreographer.doCallbacks(Choreographer.java:702)
	at android.view.Choreographer.doFrame(Choreographer.java:635)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6688)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by Fenox** [comment]
Fehler ist meiner Meinung nach schonmal aufgetaucht. Für jegliche Berechnungen sind min. 3 Daten-Punkte nötig, es dürfen nur arrays mit mehr als 2 Elementen übergeben werden, steht auch im Kommentar der Klasse, da der Fehler schonmal aufgetreten ist. 
Es muss vorher geprüft werden ob min. 3 Daten-Punkte vorhanden sind. (siehe Kommentar der Klasse, Methode).

**Comment by Fenox** [comment]
Bisher wurde Liskvos-Substitution principle verletzt, Kommentar zur Nutzung der Methode manipulate wurde im Interface `HRVDataManipulator` hinzugefügt

**Comment by Fenox** [comment]
Die HRVLibFacade bietet eine Methode, mit der die Validität der Daten vor der Verarbeitung geprüft werden kann (`validRRData`)
