### ISSUE TITLE
NegativeArraySizeException in SDSDCalculator

### ISSUE THREAD

**Issue by thomcz** [HRVBand/hrv-lib#5]
NegativeArraySizeException in SDSDCalculator reported by a user. This should be fixed before next version. 
**User Message: App crashes every time I want to start a measurement**

Stacktrace:
```
java.lang.NegativeArraySizeException: -1
	at hrv.calc.parameter.SDSDCalculator.process(SDSDCalculator.java:12)
	at hrv.calc.parameter.SD2Calculator.process(SD2Calculator.java:12)
	at hrv.band.app.control.HRVCalculatorFacade.getSD2(HRVCalculatorFacade.java:92)
	at hrv.band.app.control.Measurement.from(Measurement.java:199)
	at hrv.band.app.view.fragment.MeasuringFragment$ProgressBarAnimatorListener.createMeasurement(MeasuringFragment.java:433)
	at hrv.band.app.view.fragment.MeasuringFragment$ProgressBarAnimatorListener.onAnimationEnd(MeasuringFragment.java:399)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1149)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1309)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:925)
	at android.view.Choreographer.doCallbacks(Choreographer.java:702)
	at android.view.Choreographer.doFrame(Choreographer.java:635)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6688)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by Fenox** [comment]
Fehler ist durch neue Methode `validData` behoben worden. Damit kann geprüft werden ob mit den vorhandenen Daten der gewünschte Parameter berechnet werden kann oder eben nicht. (siehe commit 0f6e7daa08429ce41ee3a00a33cf710045da4cd3)
